Correct error messages
projectceladon/vendor-hardware-interfaces pull request #129
Opened 2023-10-31 05:33 UTC by jiaxuan-guo

Always got an incorrect error message of thermal deamon before. Fix it in this patch.

Tracked-On: OAM-113025

2023-10-31 05:34 UTC, cyxlily requested changes
Remove space.

2023-10-31 05:42 UTC, cyxlily approved these changes

2023-11-02 04:32 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-11-02 06:07 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-11-02 06:24 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-11-02 06:41 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2023-11-02 06:45 UTC, cyxlily approved these changes

2023-11-02 09:16 UTC, vilasrk approved these changes

2023-11-02 09:42 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-11-02 09:51 UTC, cyxlily approved these changes

2023-11-02 09:52 UTC, JeevakaPrabu reviewed
Please follow the commit message format
 
<short summary>
<blank line>
<Issue detailed>
<blank line>
<fix detailed>
<blank line>
Tracked-On:
Signed-off-by:
 
Note: Each line should be less than 72 characters

2023-11-02 10:25 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-11-02 11:12 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-11-02 13:07 UTC, sysopenci commented
Android CI has completed Engineering Build for this issue, build is SUCCESS.To merge the changes please click on APPROVE FOR MERGE button in Android CI WEB

2023-11-02 14:35 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-preintegration/builds/927

Done by "Cui, Yuxin" <yuxin.cui@intel.com>

2023-11-02 14:36 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon_smr0_master-premerge/builds/507

Done by "Cui, Yuxin" <yuxin.cui@intel.com>

2023-11-02 17:00 UTC, merged

2023-11-02 17:00 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Cui, Yuxin" <yuxin.cui@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon_smr0_master-mergerequest/builds/516