Fix cts test case "testSensorAdditionalInfo"
projectceladon/vendor-hardware-interfaces pull request #140
Opened 2024-04-29 03:06 UTC by XuBing0

Addition sensor info should not be supported on automotive sersor, include accelerometer, Gyroscope, Magnetic, add macro to disable them.

Test: run cts -m CtsSensorTestCases -t
android.hardware.cts.SensorAdditionalInfoTest#testSensorAdditionalInfo

Tracked-On: OAM-117803

2024-04-29 05:16 UTC, zhy1030 approved these changes

2024-04-29 05:20 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-04-29 07:05 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-05-07 04:12 UTC, vilasrk requested changes
Typo in commit message for Sensor.

2024-05-07 04:16 UTC, vilasrk requested changes
We are using same code base for base_aaos and caas, in that case this flag will disable needed sensors for caas

2024-05-09 05:10 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-05-09 07:54 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-05-09 08:39 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-05-10 06:27 UTC, closed without merging