Fix ATS sensors issues for base_aaos
projectceladon/vendor-hardware-interfaces pull request #153
Opened 2024-06-24 12:03 UTC by RajaniRanjan

ATS test cases were failing for uncalibrated sensors. 

1.testTypeAccelerometerUncalibrated
2.testTypeGyroscopeUnCalibrated

Test Done:
run cts -m AtsSensorsDeviceTests

Tracked-On: OAM-118805

2024-06-24 12:08 UTC, vilasrk requested changes

2024-06-24 12:08 UTC, vilasrk commented on sensors/aidl/Sensor.cpp
> +                uncal={
space needed after uncal and after "=" sign.

2024-06-24 12:08 UTC, vilasrk commented on sensors/aidl/Sensor.cpp
>                  uncal={
space needed after uncal and after "=" sign.

2024-06-24 12:08 UTC, vilasrk commented on sensors/aidl/Sensor.cpp
> +    // #ifndef FEATURE_AUTOMOTIVE
Remove commented lines if they are not part of original code.

2024-06-28 04:38 UTC, vilasrk approved these changes
LGTM

2024-06-28 04:50 UTC, sgnanase approved these changes

2024-06-28 06:15 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-06-28 08:24 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-01 05:18 UTC, balajim001 approved these changes
LGTM

2024-07-01 10:01 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-07-01 19:57 UTC, merged

2024-07-01 20:16 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/607