Add Widevine binary to Enable Widevine L3 for test
projectceladon/vendor-hardware-interfaces pull request #161
Opened 2024-08-12 07:15 UTC by HawieLong

Tracked-On: OAM-117620

2024-08-12 07:16 UTC, sysopenci commented
Improper Commit Message
Jira issue not in ['bug','improvement'],
    make sure jira issue is of type bug or improvement.

2024-08-12 07:20 UTC, sysopenci commented
Improper Commit Message
Jira issue not in ['bug','improvement'],
    make sure jira issue is of type bug or improvement.

2024-08-12 07:20 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-12 07:40 UTC, sysopenci commented
Improper Commit Message
Jira issue not in ['bug','improvement'],
    make sure jira issue is of type bug or improvement.

2024-08-12 07:40 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-13 02:35 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-13 02:35 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-13 02:36 UTC, sysopenci commented
Dependent pr program name is not compatable this pr's program name, for more details please check tracked_on

2024-08-13 07:00 UTC, feijiang1 approved these changes
LGTM

2024-08-13 07:45 UTC, JeevakaPrabu requested changes
Please call out the Tests done: in commit message

2024-08-13 08:17 UTC, HawieLong commented
> Please call out the Tests done: in commit message

Add the test message in commit and test result links are here:
http://10.239.115.76/Test_Results_share/WidevineAts/GtsExoPlayerTestCases-0813/test_result_failures_suite.html
http://10.239.115.76/Test_Results_share/WidevineCts/CtsMediaDrmFrameworkTestCases-0813/test_result_failures_suite.html

2024-08-13 08:49 UTC, JeevakaPrabu approved these changes

2024-08-13 09:27 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-13 19:04 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-08-14 00:28 UTC, merged

2024-08-14 00:46 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon_umr0_master-merge/4