Disable wakeup while polling for netlink event
projectceladon/vendor-hardware-interfaces pull request #187
Opened 2024-09-30 09:06 UTC by amarjeet-intel

Suspend fails in baremetal due to polling for
netlink event.
This Patch is to disable wakeup while polling for
netlink event.

Tests done - logs

Tracked-On: OAM-125227

2024-10-25 07:07 UTC, kaushlen approved these changes

2024-10-29 04:40 UTC, JeevakaPrabu requested changes
please detail what is meant by "logs" in Tests done

2024-11-18 07:41 UTC, JeevakaPrabu approved these changes

2024-11-18 07:52 UTC, kaushlen approved these changes

2024-11-18 08:43 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-18 08:53 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-18 09:01 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-18 09:46 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-18 10:03 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-19 05:12 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-19 08:12 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-19 08:14 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-19 08:15 UTC, sysopenci commented
one of the dependent pr cannot be Rebase and Merged; please fix the issue and commit your changes once again to run EB.

2024-11-19 09:41 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-19 15:29 UTC, sysopenci commented
FAILURE: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-21 05:11 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-21 19:35 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-21 22:18 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-22 02:19 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-22 03:02 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is FAILURE. Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-22 03:19 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-22 06:37 UTC, merged

2024-11-22 07:03 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/828