Power and stats vendor implementation
projectceladon/vendor-hardware-interfaces pull request #188
Opened 2024-10-01 06:13 UTC by shwethabolumbu

Power aidl is being moved to
vendor-hardware-interfaces

Using default AIDL for power stats hal as
is from hardware-interfaces

Tracked-On: OAM-126029

2024-10-30 05:44 UTC, vilasrk requested changes

2024-10-30 05:44 UTC, vilasrk commented on power/aidl/apex/Android.bp
> +    binaries: [
Binary name is android.hardware.power-service.intel  ,But in source binaries it is mentioned as "android.hardware.power-service.example", "android.hardware.power.stats-service.example",

2024-10-30 05:45 UTC, vilasrk requested changes

2024-10-30 05:45 UTC, vilasrk commented on power/aidl/apex/file_contexts
> +/etc(/.*)?                                                  u:object_r:vendor_configs_file:s0
Selinux permissions are not in line with binary name

2024-10-30 05:49 UTC, vilasrk requested changes

2024-10-30 05:49 UTC, vilasrk commented on power/aidl/apex/Android.bp
> +    prebuilts: [
xml name might need to change it to power-default.intel.xml?

2024-11-05 10:29 UTC, shwethabolumbu commented
Addressed the review comments. 
Moved power and stats into a common apex.

2024-11-06 07:27 UTC, kaushlen approved these changes

2024-11-06 07:48 UTC, vilasrk approved these changes
LGTM

2024-11-06 07:58 UTC, sysopenci commented
Android CI has started Engineering Build for this issue ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-06 13:23 UTC, sysopenci commented
SUCCESS: Android CI has completed Engineering Build for this issue.Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-07 10:00 UTC, sysopenci commented
Android CI has started MERGE Build for this pr ,Please check the linked Tracked-On issue/Android CI Web  for more details.

2024-11-07 13:36 UTC, merged

2024-11-07 14:02 UTC, sysopenci commented
Android CI has completed MERGE Build for this pr, build is SUCCESS. Please check the linked Tracked-On issue/Android CI Web  for more details. For Binaries: /cactus-absp-or-local/celadon-merge/807