upgrading sensors@1.0-service to sensors@2.0-service in Android_S
projectceladon/vendor-hardware-interfaces pull request #64
Opened 2022-02-28 06:59 UTC by RajaniRanjan

Tracked-On: OAM-101153
Signed-off-by: RajaniRanjan <rajani.ranjan@intel.com>

2022-03-08 10:00 UTC, rajucm2007 approved these changes
Looks good to me

2022-03-09 14:32 UTC, vilasrk approved these changes

2022-03-14 05:33 UTC, JeevakaPrabu requested changes
It would be good if you can split it into 2 commits. 1 commit that will have base sensor 2.0 code from default google implementation. 2nd commit with the changes we are introducing

2022-03-14 08:12 UTC, RajaniRanjan commented
> It would be good if you can split it into 2 commits. 1 commit that will have base sensor 2.0 code from default google implementation. 2nd commit with the changes we are introducing

its a port from android r to s , original changes was done by @rajucm2007

2022-03-20 04:29 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4110

2022-03-20 07:43 UTC, sysopenci reviewed
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4111

2022-03-20 12:52 UTC, sysopenci reviewed
PR integrated into 'preintegration' builder



More details, logs, and binaries: /absp/builders/celadon-preintegration/builds/4112

Done by "Ranjan, Rajani" <rajani.ranjan@intel.com>

2022-03-21 04:21 UTC, sysopenci reviewed
PR integrated into 'premerge' builder



More details, logs, and binaries: /absp/builders/celadon-premerge/builds/2307

Done by "Ranjan, Rajani" <rajani.ranjan@intel.com>

2022-03-21 07:42 UTC, merged

2022-03-21 07:43 UTC, sysopenci reviewed
cactus finished building and testing your changes 

It was requested for merge by "Ranjan, Rajani" <rajani.ranjan@intel.com> 

so we merge it. Thanks for your contribution.

more details, logs, and binaries: /absp/builders/celadon-mergerequest/builds/2781